version: '3.8'

services:
  
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: TD0Bf4krC5VWGt4vyyB$
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"